version: '3.8'

services:
  manager:
    build:
      context: .
      dockerfile: manager-service/Dockerfile
    networks:
      - app-network
    depends_on:
      - worker
    ports:
      - "8080:8080"


  worker:
    build:
      context: .
      dockerfile: worker-service/Dockerfile
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - worker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
